server:
  port: 18084

spring:
  application:
    name: 5-function

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      document-index-name: ${AI_DASHSCOPE_DOCUMENT_INDEX_NAME}

logging:
  level:
    org.springframework.ai: DEBUG
