### 发送邮件
GET http://localhost:18084/hello?prompt=帮我写一封电子邮件，发送给94xinkong@gmail.com。邮件主题是“关于我的简历”，邮件内容是“您好，我是星空，我在贵公司看到您的招聘信息，对贵公司的职位非常感兴趣，希望能够加入贵公司，为贵公司的发展贡献自己的力量。我的简历请见附件，如有需要，请随时联系我。谢谢！”。

### 获取天气信息
GET http://localhost:18084/hello?prompt=今日乌鲁木齐的天气如何？给出一些穿衣建议。

### 多个函数组合调用
GET http://localhost:18084/hello?prompt=首先获取今日重庆的天气情况，然后将结果发送给94xinkong@gmail.com。


