server:
  port: 18084

spring:
  application:
    name: 5-function

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

logging:
  level:
    org.springframework.ai: DEBUG

# 这里使用了阿里云的邮箱
mail:
  host: smtp.aliyun.com
  port: 465
  from: ${MAIL_USERNAME}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

# 使用和风天气的api-key：https://console.qweather.com/
weather:
  api:
    api-key: ${HEFENG_WEATHER_API_KEY}
